INSERT OR IGNORE INTO app_users (id, email, display_name, locale, status) VALUES
  ('user_admin_wembla', 'daniel@wembla.com', 'Daniel Wembla', 'es-HN', 'invited'),
  ('user_admin_dachavarriam', 'dachavarriam@gmail.com', 'Daniel Chavarría', 'es-HN', 'invited');

UPDATE app_users
SET status = 'invited', updated_at = CURRENT_TIMESTAMP
WHERE email IN ('daniel@wembla.com', 'dachavarriam@gmail.com');

INSERT OR IGNORE INTO user_roles (user_id, role, school_id)
SELECT id, 'admin', 'school_eis'
FROM app_users
WHERE email IN ('daniel@wembla.com', 'dachavarriam@gmail.com');

INSERT OR IGNORE INTO classrooms (id, school_id, grade, section, classroom_name, building, guide_teacher) VALUES
  ('class_eis_nursery_a', 'school_eis', 'Nursery', 'A', 'Nursery A', NULL, 'Por confirmar'),
  ('class_eis_nursery_b', 'school_eis', 'Nursery', 'B', 'Nursery B', NULL, 'Por confirmar'),
  ('class_eis_nursery_c', 'school_eis', 'Nursery', 'C', 'Nursery C', NULL, 'Por confirmar'),
  ('class_eis_nursery_d', 'school_eis', 'Nursery', 'D', 'Nursery D', NULL, 'Por confirmar'),
  ('class_eis_nursery_e', 'school_eis', 'Nursery', 'E', 'Nursery E', NULL, 'Por confirmar'),
  ('class_eis_prekinder_a', 'school_eis', 'Prekinder', 'A', 'Prekinder A', NULL, 'Por confirmar'),
  ('class_eis_prekinder_b', 'school_eis', 'Prekinder', 'B', 'Prekinder B', NULL, 'Por confirmar'),
  ('class_eis_prekinder_c', 'school_eis', 'Prekinder', 'C', 'Prekinder C', NULL, 'Por confirmar'),
  ('class_eis_prekinder_d', 'school_eis', 'Prekinder', 'D', 'Prekinder D', NULL, 'Por confirmar'),
  ('class_eis_prekinder_e', 'school_eis', 'Prekinder', 'E', 'Prekinder E', NULL, 'Por confirmar'),
  ('class_eis_kinder_a', 'school_eis', 'Kinder', 'A', 'Kinder A', NULL, 'Por confirmar'),
  ('class_eis_kinder_b', 'school_eis', 'Kinder', 'B', 'Kinder B', NULL, 'Por confirmar'),
  ('class_eis_kinder_c', 'school_eis', 'Kinder', 'C', 'Kinder C', NULL, 'Por confirmar'),
  ('class_eis_kinder_d', 'school_eis', 'Kinder', 'D', 'Kinder D', NULL, 'Por confirmar'),
  ('class_eis_kinder_e', 'school_eis', 'Kinder', 'E', 'Kinder E', NULL, 'Por confirmar'),
  ('class_eis_grade_1_a', 'school_eis', '1°', 'A', '1° A', NULL, 'Por confirmar'),
  ('class_eis_grade_1_b', 'school_eis', '1°', 'B', '1° B', NULL, 'Por confirmar'),
  ('class_eis_grade_1_c', 'school_eis', '1°', 'C', '1° C', NULL, 'Por confirmar'),
  ('class_eis_grade_1_d', 'school_eis', '1°', 'D', '1° D', NULL, 'Por confirmar'),
  ('class_eis_grade_1_e', 'school_eis', '1°', 'E', '1° E', NULL, 'Por confirmar'),
  ('class_eis_grade_2_a', 'school_eis', '2°', 'A', '2° A', NULL, 'Por confirmar'),
  ('class_eis_grade_2_b', 'school_eis', '2°', 'B', '2° B', NULL, 'Por confirmar'),
  ('class_eis_grade_2_c', 'school_eis', '2°', 'C', '2° C', NULL, 'Por confirmar'),
  ('class_eis_grade_2_d', 'school_eis', '2°', 'D', '2° D', NULL, 'Por confirmar'),
  ('class_eis_grade_2_e', 'school_eis', '2°', 'E', '2° E', NULL, 'Por confirmar'),
  ('class_eis_grade_3_a', 'school_eis', '3°', 'A', '3° A', NULL, 'Por confirmar'),
  ('class_eis_grade_3_b', 'school_eis', '3°', 'B', '3° B', NULL, 'Por confirmar'),
  ('class_eis_grade_3_c', 'school_eis', '3°', 'C', '3° C', NULL, 'Por confirmar'),
  ('class_eis_grade_3_d', 'school_eis', '3°', 'D', '3° D', NULL, 'Por confirmar'),
  ('class_eis_grade_3_e', 'school_eis', '3°', 'E', '3° E', NULL, 'Por confirmar'),
  ('class_eis_grade_4_a', 'school_eis', '4°', 'A', '4° A', NULL, 'Por confirmar'),
  ('class_eis_grade_4_b', 'school_eis', '4°', 'B', '4° B', NULL, 'Por confirmar'),
  ('class_eis_grade_4_c', 'school_eis', '4°', 'C', '4° C', NULL, 'Por confirmar'),
  ('class_eis_grade_4_d', 'school_eis', '4°', 'D', '4° D', NULL, 'Por confirmar'),
  ('class_eis_grade_4_e', 'school_eis', '4°', 'E', '4° E', NULL, 'Por confirmar'),
  ('class_eis_grade_5_a', 'school_eis', '5°', 'A', '5° A', NULL, 'Por confirmar'),
  ('class_eis_grade_5_b', 'school_eis', '5°', 'B', '5° B', NULL, 'Por confirmar'),
  ('class_eis_grade_5_c', 'school_eis', '5°', 'C', '5° C', NULL, 'Por confirmar'),
  ('class_eis_grade_5_d', 'school_eis', '5°', 'D', '5° D', NULL, 'Por confirmar'),
  ('class_eis_grade_5_e', 'school_eis', '5°', 'E', '5° E', NULL, 'Por confirmar'),
  ('class_eis_grade_6_a', 'school_eis', '6°', 'A', '6° A', NULL, 'Por confirmar'),
  ('class_eis_grade_6_b', 'school_eis', '6°', 'B', '6° B', NULL, 'Por confirmar'),
  ('class_eis_grade_6_c', 'school_eis', '6°', 'C', '6° C', NULL, 'Por confirmar'),
  ('class_eis_grade_6_d', 'school_eis', '6°', 'D', '6° D', NULL, 'Por confirmar'),
  ('class_eis_grade_6_e', 'school_eis', '6°', 'E', '6° E', NULL, 'Por confirmar'),
  ('class_eis_grade_7_a', 'school_eis', '7°', 'A', '7° A', NULL, 'Por confirmar'),
  ('class_eis_grade_7_b', 'school_eis', '7°', 'B', '7° B', NULL, 'Por confirmar'),
  ('class_eis_grade_7_c', 'school_eis', '7°', 'C', '7° C', NULL, 'Por confirmar'),
  ('class_eis_grade_7_d', 'school_eis', '7°', 'D', '7° D', NULL, 'Por confirmar'),
  ('class_eis_grade_7_e', 'school_eis', '7°', 'E', '7° E', NULL, 'Por confirmar'),
  ('class_eis_grade_8_a', 'school_eis', '8°', 'A', '8° A', NULL, 'Por confirmar'),
  ('class_eis_grade_8_b', 'school_eis', '8°', 'B', '8° B', NULL, 'Por confirmar'),
  ('class_eis_grade_8_c', 'school_eis', '8°', 'C', '8° C', NULL, 'Por confirmar'),
  ('class_eis_grade_8_d', 'school_eis', '8°', 'D', '8° D', NULL, 'Por confirmar'),
  ('class_eis_grade_8_e', 'school_eis', '8°', 'E', '8° E', NULL, 'Por confirmar'),
  ('class_eis_grade_9_a', 'school_eis', '9°', 'A', '9° A', NULL, 'Por confirmar'),
  ('class_eis_grade_9_b', 'school_eis', '9°', 'B', '9° B', NULL, 'Por confirmar'),
  ('class_eis_grade_9_c', 'school_eis', '9°', 'C', '9° C', NULL, 'Por confirmar'),
  ('class_eis_grade_9_d', 'school_eis', '9°', 'D', '9° D', NULL, 'Por confirmar'),
  ('class_eis_grade_9_e', 'school_eis', '9°', 'E', '9° E', NULL, 'Por confirmar'),
  ('class_eis_grade_10_a', 'school_eis', '10°', 'A', '10° A', NULL, 'Por confirmar'),
  ('class_eis_grade_10_b', 'school_eis', '10°', 'B', '10° B', NULL, 'Por confirmar'),
  ('class_eis_grade_10_c', 'school_eis', '10°', 'C', '10° C', NULL, 'Por confirmar'),
  ('class_eis_grade_10_d', 'school_eis', '10°', 'D', '10° D', NULL, 'Por confirmar'),
  ('class_eis_grade_10_e', 'school_eis', '10°', 'E', '10° E', NULL, 'Por confirmar'),
  ('class_eis_grade_11_a', 'school_eis', '11°', 'A', '11° A', NULL, 'Por confirmar'),
  ('class_eis_grade_11_b', 'school_eis', '11°', 'B', '11° B', NULL, 'Por confirmar'),
  ('class_eis_grade_11_c', 'school_eis', '11°', 'C', '11° C', NULL, 'Por confirmar'),
  ('class_eis_grade_11_d', 'school_eis', '11°', 'D', '11° D', NULL, 'Por confirmar'),
  ('class_eis_grade_11_e', 'school_eis', '11°', 'E', '11° E', NULL, 'Por confirmar');

